# Generated by Django 5.1.4 on 2025-01-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientrequest',
            old_name='expected_budget',
            new_name='predicted_budget',
        ),
        migrations.RemoveField(
            model_name='clientrequest',
            name='description',
        ),
        migrations.AddField(
            model_name='clientrequest',
            name='project_complexity',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='clientrequest',
            name='project_duration',
            field=models.IntegerField(default=4),
        ),
    ]
